sudo: requires
compiler: gcc
dist: trusty


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: |
  set -ex
  g++ --version
  cmake --version
  mkdir build 
  cd build 
  cmake ..
  make
